---
- name: debian
  hosts: debian-hosts
  roles:
    - sudo
    - common

- name: pi
  hosts: pi-hosts
  roles:
    - sudo
    - common

- name: apcupsd
  hosts: apcupsd-hosts
  roles:
    - apcupsd

- name: docker
  hosts: docker-hosts
  roles:
    - docker

- name: portainer
  hosts: portainer-hosts
  roles:
    - portainer

- name: traefik
  hosts: traefik-hosts
  roles:
    - traefik