---
- name: debian
  hosts: debian-hosts
  roles:
    - sudo
    - common

- name: pi
  hosts: pi-hosts
  roles:
    - sudo
    - common

- name: docker
  hosts: docker-hosts
  roles:
    - docker

- name: media
  hosts: media-hosts
  roles:
    - media-server
