---
- name: debian
  hosts: debian-hosts
  roles:
    - sudo
    - debian

- name: docker
  hosts: docker-hosts
  roles:
    - docker

- name: docker-compose
  hosts: docker-compose-hosts
  roles:
    - docker-compose

- name: portainer
  hosts: portainer-hosts
  roles:
    - portainer

- name: traefik
  hosts: traefik-hosts
  roles:
    - traefik

- name: netbootxyz
  hosts: netbootxyz-hosts
  roles:
    - netbootxyz

- name: samba
  hosts: samba-hosts
  roles:
    - samba

- name: apcupsd
  hosts: apcupsd-hosts
  roles:
    - apcupsd