---
- name: debian
  hosts: debian-hosts
  roles:
    - sudo
    - common

- name: pi
  hosts: pi-hosts
  roles:
    - sudo
    - common

- name: apcupsd
  hosts: apcupsd-hosts
  roles:
    - apcupsd

- name: docker-test
  hosts: test
  roles:
    - docker
