---
services:
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /Apps/sabnzbd/config:/config
      - /mnt/md0/Downloads:/Downloads #optional
    ports:
      - 8080:8080
    restart: unless-stopped
  prowlarr:
    container_name: prowlarr
    image: ghcr.io/hotio/prowlarr:latest
    ports:
      - "9696:9696"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/London
    volumes:
      - /Apps/prowlarr/config:/config
    restart: unless-stopped
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /Apps/sonarr/config:/config
      - /mnt/md0/Video/Series:/tv #optional
      - /mnt/md0/Downloads:/Downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped
  radarr:
    container_name: radarr
    image: ghcr.io/hotio/radarr:latest
    ports:
      - "7878:7878"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/London
    volumes:
      - /Apps/radarr/config:/config
      - /mnt/md0/Video/Movies:/Movies
      - /mnt/md0/Downloads:/Downloads #optional  
    restart: unless-stopped
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /Apps/lidarr/appdata/config:/config
      - /mnt/md0/Audio/Music:/Music #optional
      - /mnt/md0/Downloads:/Downloads #optional
    ports:
      - 8686:8686
    restart: unless-stopped
