---
services:
  plex:
    container_name: plex
    image: plexinc/pms-docker:latest
    restart: unless-stopped
    ports:
      - 32400:32400/tcp
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
    environment:
      - TZ=Europe/London
      - PLEX_CLAIM=PLEX_CLAIM #https://www.plex.tv/claim
      - ADVERTISE_IP=http://192.168.1.16:32400/
    hostname: n100
    volumes:
      - /Apps/plex/config:/config
      - /tmp/transcode:/transcode
      - /media/md0/Audio/Music:/Music
      - /media/md0/Video/Movies:/Movies
      - /media/md0/Video/Series:/Series
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    ports:
      - 8096:8096
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
    volumes:
      - /Apps/jellyfin/config:/config
      - /media/md0/Audio/Music:/Music
      - /media/md0/Video/Movies:/Movies
      - /media/md0/Video/Series:/Series
    restart: 'unless-stopped'
    environment:
      - JELLYFIN_PublishedServerUrl=http://n100:8096 # Optional - alternative address used for autodiscovery
