---
services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    network_mode: 'host'
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
    volumes:
      - /Apps/jellyfin/config:/config
      - /media/md0/Audio/Music:/Music
      - /media/md0/Video/Movies:/Movies
      - /media/md0/Video/Series:/Series
    restart: 'unless-stopped'
    # Optional - alternative address used for autodiscovery
    environment:
      - JELLYFIN_PublishedServerUrl=http://n100:8096
    # Optional - may be necessary for docker healthcheck to pass if running in host network mode
    extra_hosts:
      - 'host.docker.internal:host-gateway'
