---
services:
  plex:
    container_name: plex
    image: plexinc/pms-docker:latest
    restart: unless-stopped
    ports:
      - 32400:32400/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    environment:
      - TZ=Europe/London
      - PLEX_CLAIM=PLEX_CLAIM #https://www.plex.tv/claim
      - ADVERTISE_IP=http://192.168.1.11:32400/
    hostname: node
    volumes:
      - /mnt/md0/Apps/plex/config:/config
      - /media/md0/Audio/Music:/Music
      - /media/md0/Video/Movies:/Movies
      - /media/md0/Video/Series:/Series
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    ports:
      - 8096:8096
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
    volumes:
      - /Apps/jellyfin/config:/config
      - /media/md0/Audio/Music:/Music
      - /media/md0/Video/Movies:/Movies
      - /media/md0/Video/Series:/Series
    restart: 'unless-stopped'
    # Optional - alternative address used for autodiscovery
    environment:
      - JELLYFIN_PublishedServerUrl=http://n100:8096
