---
- name: install cockpit
  apt:
    name: cockpit
  become: true

- name: install tmux
  apt: 
    name: tmux
  become: true

- name: install ca-certificates
  apt: 
    name: ca-certificates
  become: true

- name: install curl
  apt: 
    name: curl
  become: true
