---
- name: deploy host docker compose
  copy:
    src: files/{{inventory_hostname}}/
    dest: ./{{inventory_hostname}}/

- name: docker compose up
  shell:
    cmd: "docker compose -f ./{{inventory_hostname}}/docker-compose.yml up -d"
