---
- name: deploy traefik docker compose
  copy:
    src: files/
    dest: /Apps/traefik/
  become: true

- name: docker compose up
  shell:
    cmd: "docker compose -f /Apps/traefik/docker-compose.yml up -d"
