---
- name: deploy plex docker-compose
  template:
    src: templates/docker-compose.yml.j2
    dest: /Apps/plex/docker-compose.yml
    owner: {{ansible_user}}
    group: {{ansible_user}}
    mode: '0644'
  become: true

- name: docker compose up
  shell:
    cmd: "docker compose -f /Apps/plex/docker-compose.yml up -d"
